### ISSUE TITLE
JCommander should allow a custom service to provide instances of IStringConverterFactory

### ISSUE THREAD

**Issue by ocean7** [cbeust/jcommander#196]
JCommander supports custom types but it does so in the form of Class<?> objects that are attached to parameters or through converter factories. That's fine but there's no way to customize how those Class<?> objects are instantiated. Presumably JCommander is just using standard reflection to newInstance() up the converters but this is limited; it would be nice to provide a custom instantiator which could actually go out to a dependency injection framework to return an instance of these converter factories.

**Comment by lukehb** [comment]
I agree, this limitation means that IStringConverter cannot have a constructor that takes arguments. Which, in turn, limits the types that can actually be converted to - i.e. some types require some other object instance in order to make the string to object conversion.

Changing the method signature of IStringConverterFactory would be enough I think:

<T> IStringConverter<T> getConverter(Class<T> forType);

Instead of returning the class, return the actual converter object. This would allow the factory to be created with whatever objects are required and pass them into each converter as needed.

**Comment by cbeust** [comment]
Yes, this would work but I can't change the signature of
`IStringConverterFactory` or it would break existing clients. I could
create an `IStringConverterFactory2`.


-- 
Cédric

**Comment by lukehb** [comment]
Yup, that works :+1:

**Comment by simon04** [comment]
This issue can be closed now.
