### ISSUE TITLE
Argument value starting by '@' is catch by jcommander

### ISSUE THREAD

**Issue by asyd** [cbeust/jcommander#198]
Hi, 

I need an argument that start by @ (like for search all users belonging to an email domain), but this character seems to be catches by commander to read arguments from a file.

- "@value" is catch by jcommander, so I've got an FileNotFoundException
- '@value' include the ''
- "\@value" include the \

Thanks!

**Comment by bacar** [comment]
Is it difficult to patch jcommander to use eg @@ as an escape sequence?

**Comment by cbeust** [comment]
No but it would break a lot of existing users...

**Comment by bacar** [comment]
It would only break for people already using @@ as a prefix eg to load from an args file called "@args". Is that likely to be a lot of users?

Still, worth avoiding where possible - if implementing the proposed alternative, is it not also worthwhile to introduce escaping at the same time? (Is there someone out there who has _no_ spare special characters left?)

On a related note - I don't know there's already an issue for this but it would be useful if there were some way for nested "@" includes to load args files relative to their including file as opposed to relative to the working directory, otherwise it's only possible to use the args file from a particular working directory.

**Comment by asyd** [comment]
imho jcommander simply should expose a method to override the symbol used, that won't break existing applications.

**Comment by TKlerx** [comment]
Why would '@@' break existing code if you check for '@' and '@@'?
Do you think that some people name their files '@@foo'?

**Comment by tfiskgul** [comment]
This issue is solved in this pull request, and should be closed.

https://github.com/cbeust/jcommander/pull/156
