### ISSUE TITLE
Document mutually exclusive parameters

### ISSUE THREAD

**Issue by wedi** [cbeust/jcommander#272]
Hi!
Firstofall thanks for your great framework. It's so cool and easy to use! 👍 
I'd like to suggest that you add a short hint to the documentation about mutually exclusive parameters. Now I read #41 and understand your reasoning as it's really not a problem to implement it by oneself.

Still I was about to open an issue about this and others are likely to search for this as well.

**Comment by wedi** [comment]
Fixed by 2f5150988da0b968cbfb1e0e71d999fb0ca31618.

**Comment by SomethingReallyRandom** [comment]
The tag line to jcommander is "Because life is too short to parse command line parameters". But it seems to me that's not the case for mutually exclusive parameters.
I would have thought that this approach of handling this outside of jcommander would result in the help syntax of the command being wrong too.

Wouldn't a simple approach be to add a parameter to the Parameter annotation called Group, were you could provide a string which is used to identify a group across parameters. Then when parsing the parameters enforce that you can only have one parameter from a group.  i.e.
```java
@Parameter(names = { "-e", "--encrypt" }, description = "encrypt and encode plaintext value", group="exclusiveCommand")
String plainText=null;
@Parameter(names = { "-d", "--decrypt" }, description = "decode and decrypt ciphertext value", group="exclusiveCommand")
String cipherText=null;
```

**Comment by acostalima** [comment]
> The tag line to jcommander is "Because life is too short to parse command line parameters". But it seems to me that's not the case for mutually exclusive parameters.
> I would have thought that this approach of handling this outside of jcommander would result in the help syntax of the command being wrong too.
> 
> Wouldn't a simple approach be to add a parameter to the Parameter annotation called Group, were you could provide a string which is used to identify a group across parameters. Then when parsing the parameters enforce that you can only have one parameter from a group. i.e.

This has already been going through multiple discussions. Furthermore, please take a look at the [documentation](http://jcommander.org/#_global_parameter_validation). 
Moreover, considering your use case, I'd suggest to create, instead of options in the same command, two distinct commands, encrypt and decrypt, so you can avoid post-validation.
