### ISSUE TITLE
Support line breaks in description?

### ISSUE THREAD

**Issue by Mygod** [cbeust/jcommander#308]
If would be nice if you can properly support line breaks in description.

**Comment by jeremysolarz** [comment]
@cbeust what do you say, should this be implemented?

**Comment by cbeust** [comment]
Not really convinced, it's the first time this comes up so there doesn't seem to be a big demand for this feature.

**Comment by jeremysolarz** [comment]
@cbeust close it than as "Do not fix"?

**Comment by Mygod** [comment]
Well, it isn't hard to implement anyway? Or what do you suggest me to use instead?

**Comment by jeremysolarz** [comment]
@Mygod Sorry for the misunderstanding. Which description are you talking about btw.?

If you are talking about the `@Parameter(description="...")` then you can use usual characters `\n` like for line breaks.

**Comment by Mygod** [comment]
Yes that's exactly what I'm talking about. And yes it works but the problem is that the padding is all wrong.

**Comment by jeremysolarz** [comment]
@Mygod understood. I guess as a workaround you can simply add 6 spaces (this is the amount of spaces added what I can see in the source) per indentation level.

I know it's not optimal. 

I guess the best solution would be to change description in a `String[]` but since this would break the contract to the existing API this is a no go. Other alternative is to introduce a field like `multiLineDescription` but that looks ugly imho.

@cbeust what do you say?

**Comment by Mygod** [comment]
The problem is that jcommander will try to wrap my description unaware of the line break. The best workaround I can achieve is by adding lots of spaces and ending up with a very ugly and unmaintainable code.

**Comment by jeremysolarz** [comment]
@Mygod well thinking about it further changing it to `String[]` would actually not break backwards compatibility. Let's see what @cbeust says.

**Comment by jeremysolarz** [comment]
@cbeust shall this be closed or changed?

**Comment by virgo47** [comment]
I got here because of the indentation problem with \n which makes it ugly/unusable. I'll probably rather not use \n and have longer descriptions as a single blob.
