### ISSUE TITLE
Fuzzy finder command options

### ISSUE THREAD

**Issue by theonlygusti** [cbeust/jcommander#319]
Allow some way for users to either extend or otherwise enable the ability to have JCommander use a fuzzy finder for its command options.

**Comment by jeremysolarz** [comment]
Dear @theonlygusti,

This sounds like a rather special case. I guess implementing this is a bit out of scope for `JCommander`.

@cbeust what do you say?

**Comment by theonlygusti** [comment]
@jeremysolarz Yes, it is a bit special case. I feel  like it could be useful though to make the command tokenizer/parser (or whatever the correct terminology is) extendable.

**Comment by jeremysolarz** [comment]
@theonlygusti 
One more thing. Did you notice `JCommander#setAllowAbbreviatedOptions` in the [documentation](http://jcommander.org/#_other_option_configurations) that's something similar to what you want I guess

**Comment by theonlygusti** [comment]
@jeremysolarz oh wow, no I didn't notice that on my couple readings.

That's really helpful to me, thank you!

**Comment by jeremysolarz** [comment]
@theonlygusti since the requested change would be quite extensive, let's keep if like it is for now.

**Comment by cbeust** [comment]
Note that I recently refactored how JCommander parses options (they are no longer required to start with a hyphen) so as a consequence of this, implementing various algorithms to identify options has become a lot easier.

I'm beginning to think it would be trivial to let the user supply their own version of the `isOption()` method, which they could pass at instantiation time.

Having said that, identifying an option is still a bit tricky because of the many options that JCommander offers:

https://github.com/cbeust/jcommander/blob/master/src/main/java/com/beust/jcommander/JCommander.java#L412-L450

Preserving this behavior might be a bit tricky for the user.

**Comment by jeremysolarz** [comment]
@cbeust I thin we can close this right?

**Comment by jeremysolarz** [comment]
@cbeust I think this can be closed right?
