### ISSUE TITLE
Publishing latest release

### ISSUE THREAD

**Issue by mkarg** [cbeust/jcommander#552]
@cbeust Latest release is many months old, so I would kindly propose publishing the latest changest added by me and others. Thanks.

**Comment by yeroc** [comment]
See also #534.  Would like to help if I can as I've also been waiting more than 6 months for some fixes.

**Comment by mkarg** [comment]
@cbeust Can you please share your ideas with us why not publishing the latest release? Is there a specific schedule we do not know of?

**Comment by cbeust** [comment]
Hi Markus,

My only excuse is that I have a lot of things going on right now which have prevented me from releasing that new version. Will do my best to make this happen soon, but in the meantime, I'd love to explore how I can make you a release manager as well, so that you can release a new version of JCommander whenever you think makes sense.

How can we make this happen?

**Comment by mkarg** [comment]
Cedric, I would feel honoured to become a realease manager. What we need for this is IMHO the following:
* Committer rights for my user on Github, as releasing implies creating branches and pushing release numbers
* I assume you release via OSSRH, so we need to create a ticket for [OSSRH JIRA](https://issues.sonatype.org/) that asks to add my OSSRH user to press the release button for the group ID `com.beust` (unfortunately JCommander is not using `com.beust.jcommander` so you need to trust me more than essentially needed).
* It would be nice if you could briefly sketch the technical commands you actually apply to release JCommander, as there are plenty of solutions we could perform this, but it makes sense if I do it the same way you did it so far.
* You should script some brief rules that outline a policy how you want me to manage the releases, so I am acting in the sense you intend it. For example, minimum time between release or list of tests to pass before releasing.

**Comment by cbeust** [comment]
Thanks for the suggestions, Markus. Can you email me at cbeust@gmail.com? We can continue the discussion there.

**Comment by mkarg** [comment]
For the impatient: Meanwhile I am in the role of a release manager, and I am currently preparing release 1.83 together with @cbeust. Stay tuned! :-)

**Comment by yeroc** [comment]
@mkarg Thanks for doing this!  I don't suppose you have access to publish a [relocation pom](https://maven.apache.org/guides/mini/guide-relocation.html) under the old coordinates so that people will receive more-or-less automated notification that a new release has been published under new coordinates?

**Comment by mkarg** [comment]
Good idea! I will discuss this with @cbeust.
