### ISSUE TITLE
jcommander-2.0.0-RC1.jar; invalid manifest format

### ISSUE THREAD

**Issue by sysmat** [cbeust/jcommander#561]
```xml
<dependency>
            <groupId>com.beust</groupId>
            <artifactId>jcommander</artifactId>
            <version>2.0.0-RC1</version>
        </dependency>
```

- java 8

**Comment by mkarg** [comment]
Unfortunately I do not understand your bug report. Can you please explain what you did, what you expected, and what happened instead? Thanks.

BTW, there is no 2.2.0-RC1 from JCommander.

**Comment by yuanqi99** [comment]
Don't know if it is, when using Maven to package into jars, use the cmd window to run "java -jar xxx.jar --help"

 jcomd.jar; invalid manifest format
jcomd.jar中没有主清单属性
![image](https://github.com/cbeust/jcommander/assets/88283500/c2be66c1-c2a7-48a9-a7e4-d18b3e3a80fb)

**Comment by yuanqi99** [comment]
Don't know if it is, when using Maven to package into jars, use the cmd window to run "java -jar xxx.jar --help"

jcomd.jar; invalid manifest format
jcomd.jar中没有主清单属性
![image](https://github.com/cbeust/jcommander/assets/88283500/c1542be2-576b-4481-bb7a-ffb6f21233c0)

**Comment by yuanqi99** [comment]
> 不幸的是我不明白你的错误报告做了。你能解释一下你什么、你期望什么以及发生了什么吗？谢谢。
> 
> 顺便说一句，JCommander没有2.2.0-RC1。

Don't know if it is, when using Maven to package into jars, use the cmd window to run "java -jar xxx.jar --help"

jcomd.jar; invalid manifest format
jcomd.jar中没有主清单属性
![image](https://github.com/cbeust/jcommander/assets/88283500/c1542be2-576b-4481-bb7a-ffb6f21233c0)

**Comment by mkarg** [comment]
I am very sorry @yuanqi99, but I still do not understand what you are actually doing. We (Cedric and me) die not publish a release called 2.2.0-RC1 neither upload a file named jcomd.jar. So where is that jcomd.jar downloaded from?

**Comment by mkarg** [comment]
@sysmat Can you please chime in, as you wrote the initial report? Thanks.

**Comment by daveloyall** [comment]
This is the closest thing I found.  https://mvnrepository.com/artifact/com.beust/jcommander/2.0.0-RC1

Does this artifact belong to this project?  Note 2.2 vs 2.0...

**Comment by mkarg** [comment]
That page says this artifact exists only on Spring-specific repositories. We do not upload there. We officially upload only to Maven Central. Please do not ask questions *here* for stuff not produced *here*. Please always use *official* builds from Maven Central only. Thanks.

**Comment by daveloyall** [comment]
Hi mkarg, I'm new to this conversation and I'm only helping.  The question I asked was "was that artifact produced here?".  Thank you for the response.  I understand now that the artifact on spring.io is NOT official..

It is worth noting that the artifact is tagged with Cedric's first and last name.  Speculation: some third party may have attempted spread malware by "squatting" on the `groupId`, etc...  I won't be investigating that myself.  The Spring project might be interested?  They have a "report a problem" form: https://github.com/spring-projects/security-advisories/security/advisories/new

Users who downloaded the artifact in the past might want to take some action, especially if they subsequently released software which bundled that artifact...  (I say "might" because this is just speculation.)

**Comment by mkarg** [comment]
@sysmat Does that answer your question?

**Comment by mkarg** [comment]
@sysmat As you were not responding, I assume that your answer was resolved. Hence I am closing this issue.
